### ISSUE TITLE
2 very minor installation issues

### ISSUE THREAD

**Issue by zdmc23** [cairocoder01/dt-docker#1]
1. ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

SOL: Edit "./docker-compose.yml" and replace version "3" with version "2" 

2. Step 3/11 : COPY server.crt /etc/apache2/ssl/server.crt
ERROR: Service 'wordpress' failed to build: lstat server.crt: no such file or directory

SOL: Follow Step 2 (which isn't really optional).  Btw, have you considered CertBot from EFF (Let's Encrypt): https://certbot.eff.org/  I've used it on several sites recently and it's nice.  Certs expire every 90 days, but there is a daemon running to auto-update and deploy them.  No action needs to be taken.

Beyond that, it was super simple and took me less than 15 mins, and I have little-to-no experience with WordPress and Docker apart from understanding the concepts.  Nice work!

**Comment by cairocoder01** [comment]
Thanks for the notes. I'm glad it turned out to work well with little experience. 

I'll check out that version issue. I'd love to use the newest version, so I'll have to see if I can get version 3 working (or first see if I can reproduce that problem).

You're right that the certs aren't really optional. I'll remove that comment. I originally had my certs checked in to the repo, so the missing file/directory wasn't an error for me. DT requires HTTPS for API stuff, so I should make that a required step.

I'm not familiar with certbot, and in general aren't super familiar with creating certs. A quick look at the site seems like it should be simple. I created a separate issue to do at a later time so that I can close this one once I fix the other notes in here. If you're familiar with certbot and want to have a go at adding that, I'd happily accept a pull request. Otherwise, I'll try to get around to it at some point if others start using this.

**Comment by cairocoder01** [comment]
@zdmc23 Can you confirm which version of `docker-compose` you're using? `docker-compose --version` Mine is `1.22.0`.

According to this SO post, the error you got may just be related to a bad version of that utility: https://stackoverflow.com/questions/42139982/version-in-docker-compose-yml-is-unsupported-you-might-be-seeing-this-error

**Comment by zdmc23** [comment]
You're probably right:
docker-compose version 1.8.0, build unknown
